// Copyright Chaos Mesh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/chaos-mesh/chaos-mesh/api/v1alpha1"
	apiv1alpha1 "github.com/chaos-mesh/chaos-mesh/pkg/client/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeEnvoyChaoses implements EnvoyChaosInterface
type fakeEnvoyChaoses struct {
	*gentype.FakeClientWithList[*v1alpha1.EnvoyChaos, *v1alpha1.EnvoyChaosList]
	Fake *FakeApiV1alpha1
}

func newFakeEnvoyChaoses(fake *FakeApiV1alpha1, namespace string) apiv1alpha1.EnvoyChaosInterface {
	return &fakeEnvoyChaoses{
		gentype.NewFakeClientWithList[*v1alpha1.EnvoyChaos, *v1alpha1.EnvoyChaosList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("envoychaoses"),
			v1alpha1.SchemeGroupVersion.WithKind("EnvoyChaos"),
			func() *v1alpha1.EnvoyChaos { return &v1alpha1.EnvoyChaos{} },
			func() *v1alpha1.EnvoyChaosList { return &v1alpha1.EnvoyChaosList{} },
			func(dst, src *v1alpha1.EnvoyChaosList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.EnvoyChaosList) []*v1alpha1.EnvoyChaos { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.EnvoyChaosList, items []*v1alpha1.EnvoyChaos) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
