// Copyright Chaos Mesh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/chaos-mesh/chaos-mesh/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// EnvoyChaosLister helps list EnvoyChaoses.
// All objects returned here must be treated as read-only.
type EnvoyChaosLister interface {
	// List lists all EnvoyChaoses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.EnvoyChaos, err error)
	// EnvoyChaoses returns an object that can list and get EnvoyChaoses.
	EnvoyChaoses(namespace string) EnvoyChaosNamespaceLister
	EnvoyChaosListerExpansion
}

// envoyChaosLister implements the EnvoyChaosLister interface.
type envoyChaosLister struct {
	listers.ResourceIndexer[*apiv1alpha1.EnvoyChaos]
}

// NewEnvoyChaosLister returns a new EnvoyChaosLister.
func NewEnvoyChaosLister(indexer cache.Indexer) EnvoyChaosLister {
	return &envoyChaosLister{listers.New[*apiv1alpha1.EnvoyChaos](indexer, apiv1alpha1.Resource("envoychaos"))}
}

// EnvoyChaoses returns an object that can list and get EnvoyChaoses.
func (s *envoyChaosLister) EnvoyChaoses(namespace string) EnvoyChaosNamespaceLister {
	return envoyChaosNamespaceLister{listers.NewNamespaced[*apiv1alpha1.EnvoyChaos](s.ResourceIndexer, namespace)}
}

// EnvoyChaosNamespaceLister helps list and get EnvoyChaoses.
// All objects returned here must be treated as read-only.
type EnvoyChaosNamespaceLister interface {
	// List lists all EnvoyChaoses in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.EnvoyChaos, err error)
	// Get retrieves the EnvoyChaos from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.EnvoyChaos, error)
	EnvoyChaosNamespaceListerExpansion
}

// envoyChaosNamespaceLister implements the EnvoyChaosNamespaceLister
// interface.
type envoyChaosNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.EnvoyChaos]
}
